/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ChangeHistory = Array<ChangeHistoryEntry>;
export interface ChangeHistoryEntry {
  'changeType' : string,
  'date' : string,
  'description' : string,
}
export interface Employee {
  'id' : bigint,
  'fixedMonthlySalary' : [] | [number],
  'employeeType' : string,
  'hourlyRate' : number,
  'fullName' : string,
  'bankIban' : [] | [string],
  'email' : [] | [string],
  'totalAnnualLeaveDays' : bigint,
  'overtimeRate' : number,
  'phone' : [] | [string],
}
export interface EmployeeLeaveRecord {
  'remainingLeaveDays' : bigint,
  'employeeName' : string,
  'totalAnnualLeaveDays' : bigint,
  'employeeId' : bigint,
  'leaveDaysUsed' : bigint,
}
export interface EmployeePayments {
  'totalBankPayments' : number,
  'employeeName' : string,
  'payments' : Array<PaymentRecord>,
  'totalCashPayments' : number,
  'employeeId' : bigint,
}
export interface LeaveRecord {
  'remainingLeaveDays' : bigint,
  'totalAnnualLeaveDays' : bigint,
  'employeeId' : bigint,
  'leaveDaysUsed' : bigint,
}
export interface MonthlyBankSalary {
  'id' : bigint,
  'month' : bigint,
  'year' : bigint,
  'employeeId' : bigint,
  'amount' : number,
}
export interface PaymentRecord {
  'month' : bigint,
  'year' : bigint,
  'cashPayment' : number,
  'bankPayment' : number,
  'employeeId' : bigint,
  'paymentDate' : string,
}
export interface PayrollData {
  'totalBankPayments' : number,
  'month' : bigint,
  'employeeName' : string,
  'employeeType' : string,
  'year' : bigint,
  'previousMonthSalaryCarryover' : number,
  'monthlyBankFixedSalary' : [] | [number],
  'totalCashPayments' : number,
  'remainingRealSalary' : number,
  'employeeId' : bigint,
  'previousMonthBankCarryover' : number,
  'remainingBankBalance' : number,
  'normalHours' : number,
  'totalMonthlySalary' : number,
  'leaveDays' : number,
  'overtimeHours' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkDay {
  'isLeave' : boolean,
  'date' : string,
  'normalHours' : number,
  'leaveType' : [] | [string],
  'overtimeHours' : number,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addBulkLeaveDay' : ActorMethod<[string], undefined>,
  'addEmployee' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [bigint],
      [] | [string],
      [] | [string],
      [] | [string],
      string,
    ],
    bigint
  >,
  'addPayment' : ActorMethod<[PaymentRecord], undefined>,
  'addPaymentsBulk' : ActorMethod<[Array<PaymentRecord>], undefined>,
  'addWorkDay' : ActorMethod<[bigint, WorkDay], undefined>,
  'addWorkDaysBulk' : ActorMethod<[Array<[bigint, WorkDay]>], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAndUpdatePayroll' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteEmployee' : ActorMethod<[bigint], undefined>,
  'deleteLeaveRecord' : ActorMethod<[bigint, string], undefined>,
  'deleteMonthlyBankSalary' : ActorMethod<
    [bigint, bigint, bigint, bigint],
    undefined
  >,
  'deletePayment' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'deleteWorkDay' : ActorMethod<[bigint, string], undefined>,
  'getAllEmployeeLeaveRecords' : ActorMethod<[], Array<EmployeeLeaveRecord>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllEmployeesPayments' : ActorMethod<
    [bigint, bigint],
    Array<EmployeePayments>
  >,
  'getAllEmployeesPayrollData' : ActorMethod<
    [bigint, bigint],
    Array<PayrollData>
  >,
  'getAllLeaveRecords' : ActorMethod<[], Array<LeaveRecord>>,
  'getAllMonthlyBankSalaries' : ActorMethod<[], Array<MonthlyBankSalary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChangeHistoryLog' : ActorMethod<[bigint], ChangeHistory>,
  'getDailyBulkWorkDays' : ActorMethod<[string], Array<[bigint, WorkDay]>>,
  'getEmployee' : ActorMethod<[bigint], [] | [Employee]>,
  'getEmployeePayrollData' : ActorMethod<
    [bigint, bigint, bigint],
    [] | [PayrollData]
  >,
  'getLeaveRecord' : ActorMethod<[bigint], [] | [LeaveRecord]>,
  'getMonthlyBankSalary' : ActorMethod<[bigint, bigint, bigint], [] | [number]>,
  'getPayments' : ActorMethod<[bigint, bigint, bigint], Array<PaymentRecord>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkDay' : ActorMethod<[bigint, string], [] | [WorkDay]>,
  'getWorkDays' : ActorMethod<[bigint], Array<WorkDay>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'resetAllLeaveRecords' : ActorMethod<[bigint], undefined>,
  'resetLeaveRecord' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDailyBulkWorkDays' : ActorMethod<
    [string, Array<[bigint, WorkDay]>],
    undefined
  >,
  'setChangeHistoryLog' : ActorMethod<[bigint, ChangeHistory], undefined>,
  'setMonthlyBankSalariesBulk' : ActorMethod<
    [Array<[bigint, bigint, bigint, number]>],
    undefined
  >,
  'setMonthlyBankSalary' : ActorMethod<
    [bigint, bigint, bigint, number],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleLeaveDay' : ActorMethod<[bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateEmployeeWithChangeLog' : ActorMethod<[bigint, Employee], undefined>,
  'updateLeaveDaysUsed' : ActorMethod<[bigint, bigint], undefined>,
  'updateMonthlyBankSalary' : ActorMethod<
    [bigint, bigint, bigint, bigint, number],
    undefined
  >,
  'updatePayment' : ActorMethod<
    [bigint, bigint, bigint, string, PaymentRecord],
    undefined
  >,
  'updatePaymentsBulk' : ActorMethod<[Array<PaymentRecord>], undefined>,
  'updateWorkDay' : ActorMethod<[bigint, string, WorkDay], undefined>,
  'updateWorkDaysBulk' : ActorMethod<[Array<[bigint, WorkDay]>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];