/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PaymentRecord = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'cashPayment' : IDL.Float64,
  'bankPayment' : IDL.Float64,
  'employeeId' : IDL.Nat,
  'paymentDate' : IDL.Text,
});
export const WorkDay = IDL.Record({
  'isLeave' : IDL.Bool,
  'date' : IDL.Text,
  'normalHours' : IDL.Float64,
  'leaveType' : IDL.Opt(IDL.Text),
  'overtimeHours' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EmployeeLeaveRecord = IDL.Record({
  'remainingLeaveDays' : IDL.Nat,
  'employeeName' : IDL.Text,
  'totalAnnualLeaveDays' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'leaveDaysUsed' : IDL.Nat,
});
export const Employee = IDL.Record({
  'id' : IDL.Nat,
  'fixedMonthlySalary' : IDL.Opt(IDL.Float64),
  'employeeType' : IDL.Text,
  'hourlyRate' : IDL.Float64,
  'fullName' : IDL.Text,
  'bankIban' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'totalAnnualLeaveDays' : IDL.Nat,
  'overtimeRate' : IDL.Float64,
  'phone' : IDL.Opt(IDL.Text),
});
export const EmployeePayments = IDL.Record({
  'totalBankPayments' : IDL.Float64,
  'employeeName' : IDL.Text,
  'payments' : IDL.Vec(PaymentRecord),
  'totalCashPayments' : IDL.Float64,
  'employeeId' : IDL.Nat,
});
export const PayrollData = IDL.Record({
  'totalBankPayments' : IDL.Float64,
  'month' : IDL.Nat,
  'employeeName' : IDL.Text,
  'employeeType' : IDL.Text,
  'year' : IDL.Nat,
  'previousMonthSalaryCarryover' : IDL.Float64,
  'monthlyBankFixedSalary' : IDL.Opt(IDL.Float64),
  'totalCashPayments' : IDL.Float64,
  'remainingRealSalary' : IDL.Float64,
  'employeeId' : IDL.Nat,
  'previousMonthBankCarryover' : IDL.Float64,
  'remainingBankBalance' : IDL.Float64,
  'normalHours' : IDL.Float64,
  'totalMonthlySalary' : IDL.Float64,
  'leaveDays' : IDL.Float64,
  'overtimeHours' : IDL.Float64,
});
export const LeaveRecord = IDL.Record({
  'remainingLeaveDays' : IDL.Nat,
  'totalAnnualLeaveDays' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'leaveDaysUsed' : IDL.Nat,
});
export const MonthlyBankSalary = IDL.Record({
  'id' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'employeeId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ChangeHistoryEntry = IDL.Record({
  'changeType' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
});
export const ChangeHistory = IDL.Vec(ChangeHistoryEntry);
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addBulkLeaveDay' : IDL.Func([IDL.Text], [], []),
  'addEmployee' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addPayment' : IDL.Func([PaymentRecord], [], []),
  'addPaymentsBulk' : IDL.Func([IDL.Vec(PaymentRecord)], [], []),
  'addWorkDay' : IDL.Func([IDL.Nat, WorkDay], [], []),
  'addWorkDaysBulk' : IDL.Func([IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateAndUpdatePayroll' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
  'deleteLeaveRecord' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteMonthlyBankSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deletePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'deleteWorkDay' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllEmployeeLeaveRecords' : IDL.Func(
      [],
      [IDL.Vec(EmployeeLeaveRecord)],
      ['query'],
    ),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllEmployeesPayments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(EmployeePayments)],
      ['query'],
    ),
  'getAllEmployeesPayrollData' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(PayrollData)],
      ['query'],
    ),
  'getAllLeaveRecords' : IDL.Func([], [IDL.Vec(LeaveRecord)], ['query']),
  'getAllMonthlyBankSalaries' : IDL.Func(
      [],
      [IDL.Vec(MonthlyBankSalary)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangeHistoryLog' : IDL.Func([IDL.Nat], [ChangeHistory], ['query']),
  'getDailyBulkWorkDays' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
      ['query'],
    ),
  'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
  'getEmployeePayrollData' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Opt(PayrollData)],
      ['query'],
    ),
  'getLeaveRecord' : IDL.Func([IDL.Nat], [IDL.Opt(LeaveRecord)], ['query']),
  'getMonthlyBankSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Opt(IDL.Float64)],
      ['query'],
    ),
  'getPayments' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkDay' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(WorkDay)], ['query']),
  'getWorkDays' : IDL.Func([IDL.Nat], [IDL.Vec(WorkDay)], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'resetAllLeaveRecords' : IDL.Func([IDL.Nat], [], []),
  'resetLeaveRecord' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDailyBulkWorkDays' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
      [],
      [],
    ),
  'setChangeHistoryLog' : IDL.Func([IDL.Nat, ChangeHistory], [], []),
  'setMonthlyBankSalariesBulk' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64))],
      [],
      [],
    ),
  'setMonthlyBankSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleLeaveDay' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateEmployeeWithChangeLog' : IDL.Func([IDL.Nat, Employee], [], []),
  'updateLeaveDaysUsed' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateMonthlyBankSalary' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
  'updatePayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, PaymentRecord],
      [],
      [],
    ),
  'updatePaymentsBulk' : IDL.Func([IDL.Vec(PaymentRecord)], [], []),
  'updateWorkDay' : IDL.Func([IDL.Nat, IDL.Text, WorkDay], [], []),
  'updateWorkDaysBulk' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PaymentRecord = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'cashPayment' : IDL.Float64,
    'bankPayment' : IDL.Float64,
    'employeeId' : IDL.Nat,
    'paymentDate' : IDL.Text,
  });
  const WorkDay = IDL.Record({
    'isLeave' : IDL.Bool,
    'date' : IDL.Text,
    'normalHours' : IDL.Float64,
    'leaveType' : IDL.Opt(IDL.Text),
    'overtimeHours' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EmployeeLeaveRecord = IDL.Record({
    'remainingLeaveDays' : IDL.Nat,
    'employeeName' : IDL.Text,
    'totalAnnualLeaveDays' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'leaveDaysUsed' : IDL.Nat,
  });
  const Employee = IDL.Record({
    'id' : IDL.Nat,
    'fixedMonthlySalary' : IDL.Opt(IDL.Float64),
    'employeeType' : IDL.Text,
    'hourlyRate' : IDL.Float64,
    'fullName' : IDL.Text,
    'bankIban' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'totalAnnualLeaveDays' : IDL.Nat,
    'overtimeRate' : IDL.Float64,
    'phone' : IDL.Opt(IDL.Text),
  });
  const EmployeePayments = IDL.Record({
    'totalBankPayments' : IDL.Float64,
    'employeeName' : IDL.Text,
    'payments' : IDL.Vec(PaymentRecord),
    'totalCashPayments' : IDL.Float64,
    'employeeId' : IDL.Nat,
  });
  const PayrollData = IDL.Record({
    'totalBankPayments' : IDL.Float64,
    'month' : IDL.Nat,
    'employeeName' : IDL.Text,
    'employeeType' : IDL.Text,
    'year' : IDL.Nat,
    'previousMonthSalaryCarryover' : IDL.Float64,
    'monthlyBankFixedSalary' : IDL.Opt(IDL.Float64),
    'totalCashPayments' : IDL.Float64,
    'remainingRealSalary' : IDL.Float64,
    'employeeId' : IDL.Nat,
    'previousMonthBankCarryover' : IDL.Float64,
    'remainingBankBalance' : IDL.Float64,
    'normalHours' : IDL.Float64,
    'totalMonthlySalary' : IDL.Float64,
    'leaveDays' : IDL.Float64,
    'overtimeHours' : IDL.Float64,
  });
  const LeaveRecord = IDL.Record({
    'remainingLeaveDays' : IDL.Nat,
    'totalAnnualLeaveDays' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'leaveDaysUsed' : IDL.Nat,
  });
  const MonthlyBankSalary = IDL.Record({
    'id' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'employeeId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ChangeHistoryEntry = IDL.Record({
    'changeType' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
  });
  const ChangeHistory = IDL.Vec(ChangeHistoryEntry);
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addBulkLeaveDay' : IDL.Func([IDL.Text], [], []),
    'addEmployee' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addPayment' : IDL.Func([PaymentRecord], [], []),
    'addPaymentsBulk' : IDL.Func([IDL.Vec(PaymentRecord)], [], []),
    'addWorkDay' : IDL.Func([IDL.Nat, WorkDay], [], []),
    'addWorkDaysBulk' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateAndUpdatePayroll' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteEmployee' : IDL.Func([IDL.Nat], [], []),
    'deleteLeaveRecord' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteMonthlyBankSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deletePayment' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'deleteWorkDay' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllEmployeeLeaveRecords' : IDL.Func(
        [],
        [IDL.Vec(EmployeeLeaveRecord)],
        ['query'],
      ),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllEmployeesPayments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(EmployeePayments)],
        ['query'],
      ),
    'getAllEmployeesPayrollData' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(PayrollData)],
        ['query'],
      ),
    'getAllLeaveRecords' : IDL.Func([], [IDL.Vec(LeaveRecord)], ['query']),
    'getAllMonthlyBankSalaries' : IDL.Func(
        [],
        [IDL.Vec(MonthlyBankSalary)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangeHistoryLog' : IDL.Func([IDL.Nat], [ChangeHistory], ['query']),
    'getDailyBulkWorkDays' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
        ['query'],
      ),
    'getEmployee' : IDL.Func([IDL.Nat], [IDL.Opt(Employee)], ['query']),
    'getEmployeePayrollData' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Opt(PayrollData)],
        ['query'],
      ),
    'getLeaveRecord' : IDL.Func([IDL.Nat], [IDL.Opt(LeaveRecord)], ['query']),
    'getMonthlyBankSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getPayments' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkDay' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(WorkDay)], ['query']),
    'getWorkDays' : IDL.Func([IDL.Nat], [IDL.Vec(WorkDay)], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'resetAllLeaveRecords' : IDL.Func([IDL.Nat], [], []),
    'resetLeaveRecord' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDailyBulkWorkDays' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
        [],
        [],
      ),
    'setChangeHistoryLog' : IDL.Func([IDL.Nat, ChangeHistory], [], []),
    'setMonthlyBankSalariesBulk' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64))],
        [],
        [],
      ),
    'setMonthlyBankSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleLeaveDay' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateEmployeeWithChangeLog' : IDL.Func([IDL.Nat, Employee], [], []),
    'updateLeaveDaysUsed' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateMonthlyBankSalary' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
    'updatePayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, PaymentRecord],
        [],
        [],
      ),
    'updatePaymentsBulk' : IDL.Func([IDL.Vec(PaymentRecord)], [], []),
    'updateWorkDay' : IDL.Func([IDL.Nat, IDL.Text, WorkDay], [], []),
    'updateWorkDaysBulk' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Nat, WorkDay))],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };