/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ChangeHistoryEntry {
    changeType: string;
    date: string;
    description: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface PayrollData {
    totalBankPayments: number;
    month: bigint;
    employeeName: string;
    employeeType: string;
    year: bigint;
    previousMonthSalaryCarryover: number;
    monthlyBankFixedSalary?: number;
    totalCashPayments: number;
    remainingRealSalary: number;
    employeeId: bigint;
    previousMonthBankCarryover: number;
    remainingBankBalance: number;
    normalHours: number;
    totalMonthlySalary: number;
    leaveDays: number;
    overtimeHours: number;
}
export interface EmployeeLeaveRecord {
    remainingLeaveDays: bigint;
    employeeName: string;
    totalAnnualLeaveDays: bigint;
    employeeId: bigint;
    leaveDaysUsed: bigint;
}
export interface PaymentRecord {
    month: bigint;
    year: bigint;
    cashPayment: number;
    bankPayment: number;
    employeeId: bigint;
    paymentDate: string;
}
export interface LeaveRecord {
    remainingLeaveDays: bigint;
    totalAnnualLeaveDays: bigint;
    employeeId: bigint;
    leaveDaysUsed: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface WorkDay {
    isLeave: boolean;
    date: string;
    normalHours: number;
    leaveType?: string;
    overtimeHours: number;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export type ChangeHistory = Array<ChangeHistoryEntry>;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface EmployeePayments {
    totalBankPayments: number;
    employeeName: string;
    payments: Array<PaymentRecord>;
    totalCashPayments: number;
    employeeId: bigint;
}
export interface MonthlyBankSalary {
    id: bigint;
    month: bigint;
    year: bigint;
    employeeId: bigint;
    amount: number;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Employee {
    id: bigint;
    fixedMonthlySalary?: number;
    employeeType: string;
    hourlyRate: number;
    fullName: string;
    bankIban?: string;
    email?: string;
    totalAnnualLeaveDays: bigint;
    overtimeRate: number;
    phone?: string;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addBulkLeaveDay(date: string): Promise<void>;
    addEmployee(fullName: string, hourlyRate: string, overtimeRate: string, fixedMonthlySalary: string | null, totalAnnualLeaveDays: bigint | null, email: string | null, phone: string | null, bankIban: string | null, employeeType: string): Promise<bigint>;
    addPayment(payment: PaymentRecord): Promise<void>;
    addPaymentsBulk(payments: Array<PaymentRecord>): Promise<void>;
    addWorkDay(employeeId: bigint, workDay: WorkDay): Promise<void>;
    addWorkDaysBulk(entries: Array<[bigint, WorkDay]>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateAndUpdatePayroll(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteEmployee(employeeId: bigint): Promise<void>;
    deleteLeaveRecord(employeeId: bigint, date: string): Promise<void>;
    deleteMonthlyBankSalary(id: bigint, employeeId: bigint, month: bigint, year: bigint): Promise<void>;
    deletePayment(employeeId: bigint, month: bigint, year: bigint, paymentDate: string): Promise<void>;
    deleteWorkDay(employeeId: bigint, date: string): Promise<void>;
    getAllEmployeeLeaveRecords(): Promise<Array<EmployeeLeaveRecord>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllEmployeesPayments(month: bigint, year: bigint): Promise<Array<EmployeePayments>>;
    getAllEmployeesPayrollData(month: bigint, year: bigint): Promise<Array<PayrollData>>;
    getAllLeaveRecords(): Promise<Array<LeaveRecord>>;
    getAllMonthlyBankSalaries(): Promise<Array<MonthlyBankSalary>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChangeHistoryLog(employeeId: bigint): Promise<ChangeHistory>;
    getDailyBulkWorkDays(date: string): Promise<Array<[bigint, WorkDay]>>;
    getEmployee(employeeId: bigint): Promise<Employee | null>;
    getEmployeePayrollData(employeeId: bigint, month: bigint, year: bigint): Promise<PayrollData | null>;
    getLeaveRecord(employeeId: bigint): Promise<LeaveRecord | null>;
    getMonthlyBankSalary(employeeId: bigint, month: bigint, year: bigint): Promise<number | null>;
    getPayments(employeeId: bigint, month: bigint, year: bigint): Promise<Array<PaymentRecord>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkDay(employeeId: bigint, date: string): Promise<WorkDay | null>;
    getWorkDays(employeeId: bigint): Promise<Array<WorkDay>>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    resetAllLeaveRecords(newAnnualLeaveDays: bigint): Promise<void>;
    resetLeaveRecord(employeeId: bigint, newAnnualLeaveDays: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyBulkWorkDays(date: string, entries: Array<[bigint, WorkDay]>): Promise<void>;
    setChangeHistoryLog(employeeId: bigint, newChangeHistory: ChangeHistory): Promise<void>;
    setMonthlyBankSalariesBulk(salaries: Array<[bigint, bigint, bigint, number]>): Promise<void>;
    setMonthlyBankSalary(employeeId: bigint, month: bigint, year: bigint, amount: number): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleLeaveDay(employeeId: bigint, date: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateEmployeeWithChangeLog(employeeId: bigint, updatedEmployee: Employee): Promise<void>;
    updateLeaveDaysUsed(employeeId: bigint, newLeaveDaysUsed: bigint): Promise<void>;
    updateMonthlyBankSalary(id: bigint, employeeId: bigint, month: bigint, year: bigint, amount: number): Promise<void>;
    updatePayment(employeeId: bigint, month: bigint, year: bigint, paymentDate: string, updatedPayment: PaymentRecord): Promise<void>;
    updatePaymentsBulk(payments: Array<PaymentRecord>): Promise<void>;
    updateWorkDay(employeeId: bigint, date: string, updatedWorkDay: WorkDay): Promise<void>;
    updateWorkDaysBulk(entries: Array<[bigint, WorkDay]>): Promise<void>;
}
import type { Employee as _Employee, LeaveRecord as _LeaveRecord, PayrollData as _PayrollData, StripeSessionStatus as _StripeSessionStatus, UserProfile as _UserProfile, UserRole as _UserRole, WorkDay as _WorkDay } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBulkLeaveDay(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBulkLeaveDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBulkLeaveDay(arg0);
            return result;
        }
    }
    async addEmployee(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: bigint | null, arg5: string | null, arg6: string | null, arg7: string | null, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
    async addPayment(arg0: PaymentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPayment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPayment(arg0);
            return result;
        }
    }
    async addPaymentsBulk(arg0: Array<PaymentRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaymentsBulk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaymentsBulk(arg0);
            return result;
        }
    }
    async addWorkDay(arg0: bigint, arg1: WorkDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkDay(arg0, to_candid_WorkDay_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkDay(arg0, to_candid_WorkDay_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addWorkDaysBulk(arg0: Array<[bigint, WorkDay]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkDaysBulk(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkDaysBulk(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateAndUpdatePayroll(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAndUpdatePayroll();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAndUpdatePayroll();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteEmployee(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteLeaveRecord(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeaveRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeaveRecord(arg0, arg1);
            return result;
        }
    }
    async deleteMonthlyBankSalary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMonthlyBankSalary(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMonthlyBankSalary(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deletePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePayment(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePayment(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteWorkDay(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkDay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkDay(arg0, arg1);
            return result;
        }
    }
    async getAllEmployeeLeaveRecords(): Promise<Array<EmployeeLeaveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeeLeaveRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeeLeaveRecords();
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployeesPayments(arg0: bigint, arg1: bigint): Promise<Array<EmployeePayments>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeesPayments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeesPayments(arg0, arg1);
            return result;
        }
    }
    async getAllEmployeesPayrollData(arg0: bigint, arg1: bigint): Promise<Array<PayrollData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployeesPayrollData(arg0, arg1);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployeesPayrollData(arg0, arg1);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllLeaveRecords(): Promise<Array<LeaveRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeaveRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeaveRecords();
            return result;
        }
    }
    async getAllMonthlyBankSalaries(): Promise<Array<MonthlyBankSalary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMonthlyBankSalaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMonthlyBankSalaries();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChangeHistoryLog(arg0: bigint): Promise<ChangeHistory> {
        if (this.processError) {
            try {
                const result = await this.actor.getChangeHistoryLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChangeHistoryLog(arg0);
            return result;
        }
    }
    async getDailyBulkWorkDays(arg0: string): Promise<Array<[bigint, WorkDay]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyBulkWorkDays(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyBulkWorkDays(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: bigint): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeePayrollData(arg0: bigint, arg1: bigint, arg2: bigint): Promise<PayrollData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeePayrollData(arg0, arg1, arg2);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeePayrollData(arg0, arg1, arg2);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaveRecord(arg0: bigint): Promise<LeaveRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveRecord(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveRecord(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyBankSalary(arg0: bigint, arg1: bigint, arg2: bigint): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyBankSalary(arg0, arg1, arg2);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyBankSalary(arg0, arg1, arg2);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayments(arg0: bigint, arg1: bigint, arg2: bigint): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayments(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayments(arg0, arg1, arg2);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkDay(arg0: bigint, arg1: string): Promise<WorkDay | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkDay(arg0, arg1);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkDay(arg0, arg1);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkDays(arg0: bigint): Promise<Array<WorkDay>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkDays(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkDays(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async resetAllLeaveRecords(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAllLeaveRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAllLeaveRecords(arg0);
            return result;
        }
    }
    async resetLeaveRecord(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetLeaveRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetLeaveRecord(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDailyBulkWorkDays(arg0: string, arg1: Array<[bigint, WorkDay]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyBulkWorkDays(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyBulkWorkDays(arg0, to_candid_vec_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setChangeHistoryLog(arg0: bigint, arg1: ChangeHistory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setChangeHistoryLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setChangeHistoryLog(arg0, arg1);
            return result;
        }
    }
    async setMonthlyBankSalariesBulk(arg0: Array<[bigint, bigint, bigint, number]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyBankSalariesBulk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyBankSalariesBulk(arg0);
            return result;
        }
    }
    async setMonthlyBankSalary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMonthlyBankSalary(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMonthlyBankSalary(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleLeaveDay(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLeaveDay(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLeaveDay(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateEmployeeWithChangeLog(arg0: bigint, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployeeWithChangeLog(arg0, to_candid_Employee_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployeeWithChangeLog(arg0, to_candid_Employee_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLeaveDaysUsed(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveDaysUsed(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveDaysUsed(arg0, arg1);
            return result;
        }
    }
    async updateMonthlyBankSalary(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyBankSalary(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyBankSalary(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePayment(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: PaymentRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePayment(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePaymentsBulk(arg0: Array<PaymentRecord>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentsBulk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentsBulk(arg0);
            return result;
        }
    }
    async updateWorkDay(arg0: bigint, arg1: string, arg2: WorkDay): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkDay(arg0, arg1, to_candid_WorkDay_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkDay(arg0, arg1, to_candid_WorkDay_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateWorkDaysBulk(arg0: Array<[bigint, WorkDay]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkDaysBulk(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkDaysBulk(to_candid_vec_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Employee_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PayrollData_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PayrollData): PayrollData {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_WorkDay_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkDay): WorkDay {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Employee | null {
    return value.length === 0 ? null : from_candid_Employee_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PayrollData]): PayrollData | null {
    return value.length === 0 ? null : from_candid_PayrollData_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveRecord]): LeaveRecord | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkDay]): WorkDay | null {
    return value.length === 0 ? null : from_candid_WorkDay_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fixedMonthlySalary: [] | [number];
    employeeType: string;
    hourlyRate: number;
    fullName: string;
    bankIban: [] | [string];
    email: [] | [string];
    totalAnnualLeaveDays: bigint;
    overtimeRate: number;
    phone: [] | [string];
}): {
    id: bigint;
    fixedMonthlySalary?: number;
    employeeType: string;
    hourlyRate: number;
    fullName: string;
    bankIban?: string;
    email?: string;
    totalAnnualLeaveDays: bigint;
    overtimeRate: number;
    phone?: string;
} {
    return {
        id: value.id,
        fixedMonthlySalary: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.fixedMonthlySalary)),
        employeeType: value.employeeType,
        hourlyRate: value.hourlyRate,
        fullName: value.fullName,
        bankIban: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.bankIban)),
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        totalAnnualLeaveDays: value.totalAnnualLeaveDays,
        overtimeRate: value.overtimeRate,
        phone: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalBankPayments: number;
    month: bigint;
    employeeName: string;
    employeeType: string;
    year: bigint;
    previousMonthSalaryCarryover: number;
    monthlyBankFixedSalary: [] | [number];
    totalCashPayments: number;
    remainingRealSalary: number;
    employeeId: bigint;
    previousMonthBankCarryover: number;
    remainingBankBalance: number;
    normalHours: number;
    totalMonthlySalary: number;
    leaveDays: number;
    overtimeHours: number;
}): {
    totalBankPayments: number;
    month: bigint;
    employeeName: string;
    employeeType: string;
    year: bigint;
    previousMonthSalaryCarryover: number;
    monthlyBankFixedSalary?: number;
    totalCashPayments: number;
    remainingRealSalary: number;
    employeeId: bigint;
    previousMonthBankCarryover: number;
    remainingBankBalance: number;
    normalHours: number;
    totalMonthlySalary: number;
    leaveDays: number;
    overtimeHours: number;
} {
    return {
        totalBankPayments: value.totalBankPayments,
        month: value.month,
        employeeName: value.employeeName,
        employeeType: value.employeeType,
        year: value.year,
        previousMonthSalaryCarryover: value.previousMonthSalaryCarryover,
        monthlyBankFixedSalary: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.monthlyBankFixedSalary)),
        totalCashPayments: value.totalCashPayments,
        remainingRealSalary: value.remainingRealSalary,
        employeeId: value.employeeId,
        previousMonthBankCarryover: value.previousMonthBankCarryover,
        remainingBankBalance: value.remainingBankBalance,
        normalHours: value.normalHours,
        totalMonthlySalary: value.totalMonthlySalary,
        leaveDays: value.leaveDays,
        overtimeHours: value.overtimeHours
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isLeave: boolean;
    date: string;
    normalHours: number;
    leaveType: [] | [string];
    overtimeHours: number;
}): {
    isLeave: boolean;
    date: string;
    normalHours: number;
    leaveType?: string;
    overtimeHours: number;
} {
    return {
        isLeave: value.isLeave,
        date: value.date,
        normalHours: value.normalHours,
        leaveType: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.leaveType)),
        overtimeHours: value.overtimeHours
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_tuple_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _WorkDay]): [bigint, WorkDay] {
    return [
        value[0],
        from_candid_WorkDay_n22(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n29(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PayrollData>): Array<PayrollData> {
    return value.map((x)=>from_candid_PayrollData_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _WorkDay]>): Array<[bigint, WorkDay]> {
    return value.map((x)=>from_candid_tuple_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkDay>): Array<WorkDay> {
    return value.map((x)=>from_candid_WorkDay_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Employee_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_WorkDay_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkDay): _WorkDay {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fixedMonthlySalary?: number;
    employeeType: string;
    hourlyRate: number;
    fullName: string;
    bankIban?: string;
    email?: string;
    totalAnnualLeaveDays: bigint;
    overtimeRate: number;
    phone?: string;
}): {
    id: bigint;
    fixedMonthlySalary: [] | [number];
    employeeType: string;
    hourlyRate: number;
    fullName: string;
    bankIban: [] | [string];
    email: [] | [string];
    totalAnnualLeaveDays: bigint;
    overtimeRate: number;
    phone: [] | [string];
} {
    return {
        id: value.id,
        fixedMonthlySalary: value.fixedMonthlySalary ? candid_some(value.fixedMonthlySalary) : candid_none(),
        employeeType: value.employeeType,
        hourlyRate: value.hourlyRate,
        fullName: value.fullName,
        bankIban: value.bankIban ? candid_some(value.bankIban) : candid_none(),
        email: value.email ? candid_some(value.email) : candid_none(),
        totalAnnualLeaveDays: value.totalAnnualLeaveDays,
        overtimeRate: value.overtimeRate,
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isLeave: boolean;
    date: string;
    normalHours: number;
    leaveType?: string;
    overtimeHours: number;
}): {
    isLeave: boolean;
    date: string;
    normalHours: number;
    leaveType: [] | [string];
    overtimeHours: number;
} {
    return {
        isLeave: value.isLeave,
        date: value.date,
        normalHours: value.normalHours,
        leaveType: value.leaveType ? candid_some(value.leaveType) : candid_none(),
        overtimeHours: value.overtimeHours
    };
}
function to_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, WorkDay]): [bigint, _WorkDay] {
    return [
        value[0],
        to_candid_WorkDay_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, WorkDay]>): Array<[bigint, _WorkDay]> {
    return value.map((x)=>to_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
